import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import { getSession } from "@/lib/auth";

const inter = localFont({
  src: "../public/fonts/Inter/Inter-VariableFont_opsz,wght.ttf",
  variable:'--font-innter'
});

const poppins = localFont({
  src: [
    {
      path:'../public/fonts/Poppins/Poppins-Thin.ttf',
      weight:'100',
      style:'normal'
    },
    {
      path:'../public/fonts/Poppins/Poppins-ExtraLight.ttf',
      weight:'200',
      style:'normal'
    },
    {
      path:'../public/fonts/Poppins/Poppins-Light.ttf',
      weight:'300',
      style:'normal'
    },
    {
      path:'../public/fonts/Poppins/Poppins-Regular.ttf',
      weight:'400',
      style:'normal'
    },
    {
      path:'../public/fonts/Poppins/Poppins-Medium.ttf',
      weight:'500',
      style:'normal'
    },
    {
      path:'../public/fonts/Poppins/Poppins-SemiBold.ttf',
      weight:'600',
      style:'normal'
    },
    {
      path:'../public/fonts/Poppins/Poppins-Bold.ttf',
      weight:'700',
      style:'normal'
    },
    {
      path:'../public/fonts/Poppins/Poppins-ExtraBold.ttf',
      weight:'800',
      style:'normal'
    },
    {
      path:'../public/fonts/Poppins/Poppins-Black.ttf',
      weight:'900',
      style:'normal'
    }
  ],
  variable:'--font-poppins'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getSession();
  let user = data
  if (!user) {
    user = null
  }
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} px-10 2xl:px-0 overflow-x-hidden scrollbar`}
      >
        <div className="sticky top-0 z-50 bg-white w-full">
            <div className="w-full ">
              <div className="max-w-[1440px] mx-auto ">
                <Navbar user={user}  />
              </div>
            </div>
            <div className="w-full h-[0.5px] bg-black opacity-30">

            </div>
          </div>
        <div className="">
          {children}
        </div>
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
